# /etc/nginx/nginx.conf
worker_processes auto;
events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    tcp_nopush    on;

    # QUIC and HTTP/3 support
    server {        
        listen 4000 ssl;
        listen [::]:4000 ssl;
        listen 4000 quic reuseport;
        listen [::]:4000 quic reuseport;
        # QUIC-specific settings
        ssl_protocols TLSv1.3;
        ssl_prefer_server_ciphers off;

        # Use your dynamically set paths here
        ssl_certificate /home/quic/quic_experiments/certs/quic-server.crt;
        ssl_certificate_key /home/quic/quic_experiments/certs/quic-server.key;
        # ssl_trusted_certificate /home/quic/quic_experiments/certs/myCA.der;
        
        # Enable client certificate verification if required
        # ssl_verify_client on;
        # ssl_client_certificate /etc/nginx/certs/client-ca.crt;

        # ssl_conf_command Curves secp256r1:secp384r1;
        # ssl_conf_command Groups X25519:P-256:P-384;
        
        # QUIC-specific settings
        ssl_session_tickets off;
        add_header Alt-Svc 'h3=":4000"; ma=86400'; # Advertise HTTP/3 support
        add_header X-Content-Type-Options nosniff;

        # Static file serving configuration
        root /www;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
